# Generated by Django 5.1.4 on 2025-01-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='idea_images/%Y/%m/%d/')),
                ('content', models.TextField()),
                ('interest', models.PositiveBigIntegerField(default=0)),
                ('devtools', models.ManyToManyField(blank=True, to='tools.devtool')),
            ],
        ),
    ]
