# Generated by Django 5.1.4 on 2025-01-15 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='devtools',
        ),
        migrations.AddField(
            model_name='idea',
            name='devtool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.devtool'),
        ),
    ]
