# Generated by Django 5.1.4 on 2025-01-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_remove_idea_devtools_idea_devtool'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
